apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: blackbox-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/maos999/cluster.git
        revision: HEAD
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/maos999/cluster.git
        targetRevision: HEAD
        path: '{{path}}'
        directory:
          recurse: true
          exclude: '{*.json}'
      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
