apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/maos999/cluster.git
    targetRevision: HEAD
    path: apps/blackbox
    
  destination: 
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
